name:                moby
version:             0.1.0.0
github:              "stites/moby"
license:             BSD3
author:              "Sam Stites"
maintainer:          "fnz@fgvgrf.vb (cipher:rot13)"
copyright:           "Copyright: (c) 2018 Sam Stites"
data-dir:            "data/"
data-files:          "*.gz"
build-type:          "Custom"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stites/moby#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - dhall
    - network-uri
    - directory
    - filepath
    - cryptonite
    - http-client
    - http-client-tls
    - http-types
    - bytestring
    - zlib
    - fgl
    - text
    - unordered-containers
    - hashtables
    - servant
    - servant-client
    - servant-server
    - mtl
    - transformers
    - aeson
    - unliftio
    - wai

executables:
  moby:
    main: Main.hs
    source-dirs: client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moby
    - optparse-applicative
    - bytestring
    - network

  mobyd:
    main: Main.hs
    source-dirs: server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moby
    - optparse-applicative
    - bytestring
    - network

tests:
  moby-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - moby

custom-setup:
  dependencies:
    - Cabal
    - http-client
    - http-client-tls
    - http-types
    - safe-exceptions
    - extra
    - base >= 4.7 && < 5
    - bytestring
    - cryptonite
    - directory
    - unordered-containers
    - filepath
    - zlib

